### ISSUE TITLE
一直下载不下来aspectjtools，是缺少啥配置吗

### ISSUE THREAD

**Issue by Tukesboy** [xing16/WanAndroid#1]
Error:A problem occurred configuring root project 'WanAndroid-master'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download aspectjtools.jar (org.aspectj:aspectjtools:1.8.9)
      > Could not get resource 'https://jcenter.bintray.com/org/aspectj/aspectjtools/1.8.9/aspectjtools-1.8.9.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/aspectj/aspectjtools/1.8.9/aspectjtools-1.8.9.jar'.
            > Remote host closed connection during handshake
   > Could not download aspectjweaver.jar (org.aspectj:aspectjweaver:1.8.9)
      > Could not get resource 'https://jcenter.bintray.com/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar'.
            > Software caused connection abort: recv failed

**Comment by xing16** [comment]
看下你的 gradle 版本是不是不一致
