### ISSUE TITLE
ARouter::There is no route match the path [/main/MainActivity], in group [main][ ] 

### ISSUE THREAD

**Issue by Arick-a** [xing16/WanAndroid#3]
当独立运行组件的时候在base中的application中做了初始化initArouter 但是当组件合并运行时并没有找到初始化Arouter在哪里
正常操作后跳转不了 报以上错误
有什么提示可以给我吗？

**Comment by xing16** [comment]
不管是作为 module 还是 app 运行，base 都是要依赖的

**Comment by Arick-a** [comment]
因为我用kotlin作为开发语言 Arouter对kotlin的依赖不同于java
