### ISSUE TITLE
资源文件的问题

### ISSUE THREAD

**Issue by Arick-a** [xing16/WanAndroid#5]
作为独立的模块 可以找到资源文件   但合并之后style指向报红，但是运行出来效果还在 不知为什么

**Comment by xing16** [comment]
> 作为独立的模块 可以找到资源文件 但合并之后style指向报红，但是运行出来效果还在 不知为什么

这个网上有解决办法

**Comment by Arick-a** [comment]
已解决 以后可能还会有问题
