### ISSUE TITLE
关于Retrofit动态添加头文件的问题

### ISSUE THREAD

**Issue by VainAnts** [xing16/WanAndroid#7]
感谢你的分享，看你的项目受益良多，有一个问题，比如我登录之后获取到一些数据我想把这些数据添加到头文件中，但我不想每次都在后续的请求中加这个@Header，我应该怎样扩展才能像OkGo这种框架可以随时设置头文件，再次感谢！

**Comment by xing16** [comment]
像登录之后 在 header 中添加 token 之类的，可以在拦截器中添加

**Comment by VainAnts** [comment]
感谢回复，下面这种方式是对的吗？ 看日志没有添加成功
![QQ图片20190725122755](https://user-images.githubusercontent.com/9073302/61846054-3e208b80-aed8-11e9-85de-13fb36e5e375.png)
